# Generated by Django 6.1 on 2026-08-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="image",
        ),
        migrations.AddField(
            model_name="profile",
            name="banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_banners/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
