# Generated by Django 6.1 on 2026-08-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="context",
            new_name="content",
        ),
    ]
