# Generated by Django 6.1 on 2026-08-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_dislikes_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="dislikes",
        ),
    ]
